### ISSUE TITLE
Future of Castle.RabbitMq

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Castle.RabbitMq#1]
This project hasn't had a commit since 31 May 2016 and has no active discussion. What is the current state and are people using it?

If no one steps forward by Friday next week to be a maintainer, I'll move it to https://github.com/castleproject-deprecated until we get a maintainer.

/cc @hammett @hconceicao

**Comment by hammett** [comment]
We use this one now: https://github.com/d-collab/RabbitMqNext

**Comment by jonorossi** [comment]
Great to hear. In that case I'm going to move the repo now since this one never had any releases.
